### ISSUE TITLE
有BUG 一直接收的话 会崩溃

### ISSUE THREAD

**Issue by sincoder** [0xE8551CCB/serial-assistant#10]
应该是数据量太大了 溢出了吧

**Comment by ShannonZ** [comment]
我也遇到了这个问题

**Comment by 0xE8551CCB** [comment]
抱歉，已经离开单片机相关领域快三年了，所以这块的话我这边很难再新增功能或修复问题，并做完整的功能测试了。另外，手头也没有 Windows 的开发环境，更难以开发。希望理解~
