### ISSUE TITLE
每次退出时不要都提醒保存设置

### ISSUE THREAD

**Issue by yisuixinq** [0xE8551CCB/serial-assistant#13]
每次退出时不要都提醒保存设置,另外发送端可以增加以十进制发送数据的选项吗?

**Comment by 0xE8551CCB** [comment]
抱歉，已经离开单片机相关领域快三年了，所以这块的话我这边很难再新增功能或修复问题，并做完整的功能测试了。另外，手头也没有 Windows 的开发环境，更难以开发。希望理解~
