### ISSUE TITLE
com3无法接收数据

### ISSUE THREAD

**Issue by liugt34** [0xE8551CCB/serial-assistant#4]
你好，按照图片上的配置，打开com3端口，点击发送，接收区没有收到任何数据，初学者，不知道是什么原因造成的，我们公司的USB接口都是禁掉的，不知道跟这个有没有关系？

**Comment by ruibinlin** [comment]
usb 禁掉了肯定收不到数据了。你要找没有禁的测试啊




在2018年01月11日 15:20，liugt34<notifications@github.com> 写道：

你好，按照图片上的配置，打开com3端口，点击发送，接收区没有收到任何数据，初学者，不知道是什么原因造成的，我们公司的USB接口都是禁掉的，不知道跟这个有没有关系？

**Comment by liugt34** [comment]
非常感谢，我找公司的运维开通一下USB接口试试。 还有前辈，我是从Web开发直接转过来做串口编程需要补习哪些知识，有没有推荐的书籍或者资料，万分感谢！

**Comment by Yohoa** [comment]
@liugt34 嗨，liugt34：
我最近也在學習串口，因此剛好可以與你分享一下我遇到的不錯的資料。

1. _Serial Port Complete_ by Jan Axelson 這本英文教材對串口介紹得非常詳細，英文不錯的話可以從這裡開始；如果你附近的圖書館沒有的話，可以在這個網站找找有沒有替代版可以下載：http://en.booksee.org
2. http://blog.csdn.net/huangshizeng/article/details/7620661 這個網頁對串口也有比較基礎的介紹。

如果你有見到感覺比較好的資料，也請你分享討論～

**Comment by 0xE8551CCB** [comment]
@liugt34 Cool, 居然从 Web 开发转去做串口编程~而我现在却在做 Web 后端。这个串口工具如果有问题的话，可能没法及时提供解决方案。手头也没有了相关的硬件和软件资源。还是感谢关注~ :)
