### ISSUE TITLE
不能记录多条字符串内容，希望能改进下

### ISSUE THREAD

**Issue by sunqianGitHub** [0xE8551CCB/serial-assistant#9]
开发中发给串口的命令有上百条，一条一条输入很不方便，希望有个侧边栏可以存储不同的命令，侧边栏长度大于窗口时可以鼠标滚轮滚动侧栏，可以模仿下SSCOM
![default](https://user-images.githubusercontent.com/30254405/39690933-5b3a19f2-520e-11e8-8e05-6e27871c6332.JPG)

**Comment by 0xE8551CCB** [comment]
抱歉，已经离开单片机相关领域快三年了，所以这块的话我这边很难再新增功能或修复问题，并做完整的功能测试了。
